version: "3.6"

services:

  db-primary:
    hostname: db-primary
    image: crunchydata/crunchy-postgres:centos7-10.3-1.8.2
    environment:
    - PGHOST=/tmp
    - MAX_CONNECTIONS=10
    - MAX_WAL_SENDERS=5
    - PG_MODE=primary
    - PG_PRIMARY_USER=primaryuser
    - PG_PRIMARY_PASSWORD=password
    - PG_DATABASE=contacts_dev
    - PG_USER=contacts_dev
    - PG_PASSWORD=contacts_dev_pass
    - PG_ROOT_PASSWORD=password
    - PG_PRIMARY_PORT=5432
    volumes:
    - db-primary-vol:/pgdata # storing data on a mapped network volume
    ports:
    - 5432
    networks:
    - db-net
    deploy:
      update_config:
        failure_action: rollback
        max_failure_ratio: .3
      placement:
        constraints:
        - node.role == manager

  #####################################################################

  db-replica:
    image: crunchydata/crunchy-postgres:centos7-10.3-1.8.2
    environment:
    - PGHOST=/tmp
    - MAX_CONNECTIONS=10
    - MAX_WAL_SENDERS=5
    - PG_MODE=replica
    - PG_PRIMARY_HOST=db-primary
    - PG_PRIMARY_PORT=5432
    - PG_PRIMARY_USER=primaryuser
    - PG_PRIMARY_PASSWORD=password
    - PG_DATABASE=contacts_dev
    - PG_USER=contacts_dev
    - PG_PASSWORD=contacts_dev_pass
    - PG_ROOT_PASSWORD=password
    volumes:
    - db-replica-vol:/pgdata # replicated data doesn't need to be stored on a mapped volume
    ports:
    - 5432
    networks:
    - db-net
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        failure_action: rollback
        max_failure_ratio: .3
      placement:
        constraints:
        - node.role == worker

  ##########################################################################

  redis:
    image: redis:4.0.11-alpine
    ports:
    - 6379:6379
    volumes:
    - redis-vol:/data
    networks:
    - redis-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
        - node.role == manager

  ################################################################################

  api:
    image: avatsaev/angular-contacts-api:dev
    ports:
    - 3000:3000
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        failure_action: rollback
        max_failure_ratio: .3
      placement:
        constraints:
        - node.role == worker
    networks:
    - db-net
    - backend-net
    - redis-net
    environment:
      DB_MASTER_URL: postgres://contacts_dev:contacts_dev_pass@db-primary/contacts_dev
      DB_REPLICAS_URL: postgres://contacts_dev:contacts_dev_pass@db-replica/contacts_dev
      REDIS_HOST: redis

  #################################################################################

  client:
    image: avatsaev/angular-contacts-client:socket
    ports:
    - 4000:80
    networks:
    - frontend-net
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        failure_action: rollback
        max_failure_ratio: .3
      placement:
        constraints:
        - node.role == worker

##################################################################

networks:
  db-net:
  frontend-net:
  backend-net:
  redis-net:

volumes:
  db-primary-vol:
  db-replica-vol:
  redis-vol: